version: "3.9"

services:
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=development

  api:
    build: .
    image: hello-graphql-api
    command: sh run.sh
    ports:
      - 3000:3000
    volumes:
      - .:/code
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=development
      - PORT=3000
      - NODE_ENV=development
    depends_on:
      - db
