version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.9-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root

  db:
    image: postgres:13-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=development

  api:
    build: .
    image: hello-graphql-api
    container_name: api
    command: sh run-dev.sh
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/code
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=postgresql://root:root@db:5432/development?schema=public
      - SECRET=some-real-secret
      - FRONT_DOMAIN=http://localhost:8000
    depends_on:
      - db
      - rabbitmq
    networks:
      - default
      - hello-graphql

networks:
  hello-graphql:
    name: hello-graphql
