version: "3.9"

services:
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=development

  api:
    build: .
    image: hello-graphql-api
    command: sh run.sh
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/code
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL="postgresql://root:root@db:5432/development?schema=public"
    depends_on:
      - db
